feat(TreeSelect):  添加TreeSelect组件。 ps:待完善搜索功能
nomui/nomui pull request #456
Opened 2021-09-10 07:35 UTC by Huzhangjie

2021-09-10 08:06 UTC, jerry-nom requested changes

2021-09-10 08:06 UTC, jerry-nom commented on components/TreeSelect/index.md
> +| multiple | 支持多选（当设置 `treeCheckable` 时自动变为 true） | `boolean ` | `true` |
multiple 跟 treeCheckable 是否保留一个就可以了？还是各有用途

2021-09-10 08:21 UTC, Huzhangjie commented on components/TreeSelect/index.md
> +| multiple | 支持多选（当设置 `treeCheckable` 时自动变为 true） | `boolean ` | `true` |
目前实现上来说。多选就必须通过Tree的 nodeCheckable。所以multiple 现在只是一个语义上让人更容易理解的一个值。

2021-09-10 08:24 UTC, Huzhangjie commented on components/TreeSelect/index.md
> +| multiple | 支持多选（当设置 `treeCheckable` 时自动变为 true） | `boolean ` | `true` |
预留treeCheckable 是为了将自定义的 Tree的 check配置抛出（比如之后可能支持Tree 级联不相关）
如果只设置multiple 的话就表明 使用默认的 nodeCheckable 配置

2021-09-10 08:48 UTC, jerry-nom commented on components/TreeSelect/index.md
> +| multiple | 支持多选（当设置 `treeCheckable` 时自动变为 true） | `boolean ` | `true` |
ok

2021-09-10 08:50 UTC, jerry-nom requested changes

2021-09-10 08:50 UTC, jerry-nom commented on components/TreeSelect/TreeSelect.js
> +        key: 'key',
key 值 设为 ‘value' 这样 options 的元素值默认是 {text:xxx,value:yyy}

2021-09-10 08:51 UTC, Huzhangjie commented on components/TreeSelect/TreeSelect.js
> +        key: 'key',
收到

2021-09-13 05:58 UTC, jerry-nom approved these changes

2021-09-13 05:58 UTC, merged